export const consolidatedMedicalEducation = {
  degrees: [
    { value: "MBBS", label: "MBBS" },
    { value: "BHMS", label: "BHMS" },
    { value: "BAMS", label: "BAMS" },
    { value: "BDS", label: "BDS" },
  ],
  postgraduateCourses: [
    { value: "MD", label: "MD" },
    { value: "MS", label: "MS" },
    { value: "DNB", label: "DNB" },
    { value: "Diploma", label: "Diploma" },
    { value: "DM", label: "DM" },
    { value: "MCh", label: "MCh" },
    { value: "Fellowship", label: "Fellowship" },
    { value: "MD/MS", label: "MD/MS" },
    { value: "MDS", label: "MDS" },
  ],
  specializations: [
    { value: "Medicine", label: "Medicine" },
    {
      value: "Dermatology, Venerology & Leprosy/DVL",
      label: "Dermatology, Venerology & Leprosy/DVL",
    },
    {
      value: "Chest & TB/Respiratory medicine",
      label: "Chest & TB/Respiratory medicine",
    },
    { value: "Psychiatry", label: "Psychiatry" },
    { value: "Pediatrics", label: "Pediatrics" },
    { value: "Radiology/Radiodiagnosis", label: "Radiology/Radiodiagnosis" },
    { value: "Anesthesia", label: "Anesthesia" },
    {
      value: "Radiotherapy/Radiation Oncology",
      label: "Radiotherapy/Radiation Oncology",
    },
    { value: "Anatomy", label: "Anatomy" },
    { value: "Physiology", label: "Physiology" },
    { value: "Pharmacology", label: "Pharmacology" },
    { value: "Microbiology", label: "Microbiology" },
    { value: "P.S.M./Community Medicine", label: "P.S.M./Community Medicine" },
    { value: "Forensic Medicine", label: "Forensic Medicine" },
    { value: "Pathology", label: "Pathology" },
    { value: "Biochemistry", label: "Biochemistry" },
    {
      value: "Transfusion Medicine/ImmunoHaematology & Blood Transfusion",
      label: "Transfusion Medicine/ImmunoHaematology & Blood Transfusion",
    },
    {
      value: "Physical Medicine & Rehabilitation",
      label: "Physical Medicine & Rehabilitation",
    },
    { value: "Palliative Medicine", label: "Palliative Medicine" },
    { value: "Nuclear Medicine", label: "Nuclear Medicine" },
    { value: "Emergency Medicine", label: "Emergency Medicine" },
    { value: "Geriatrics", label: "Geriatrics" },
    { value: "General Surgery", label: "General Surgery" },
    { value: "Orthopedics", label: "Orthopedics" },
    {
      value: "E.N.T./Otorhinolaryngology",
      label: "E.N.T./Otorhinolaryngology",
    },
    { value: "Ophthalmology", label: "Ophthalmology" },
    { value: "OBGY", label: "OBGY" },
    { value: "Cardio Thoracic Surgery", label: "Cardio Thoracic Surgery" },
    {
      value: "Dermatology and Venereology",
      label: "Dermatology and Venereology",
    },
    { value: "Pediatric Surgery", label: "Pediatric Surgery" },
    { value: "Family Medicine", label: "Family Medicine" },
    { value: "Plastic Surgery", label: "Plastic Surgery" },
    {
      value: "Health Administration Including Hospital Administration",
      label: "Health Administration Including Hospital Administration",
    },
    {
      value: "Immunohematology and Transfusion Medicine",
      label: "Immunohematology and Transfusion Medicine",
    },
    { value: "Respiratory Diseases", label: "Respiratory Diseases" },
    { value: "Neuro Surgery", label: "Neuro Surgery" },
    { value: "Rural Surgery", label: "Rural Surgery" },
    {
      value: "Social and Preventive medicine",
      label: "Social and Preventive medicine",
    },
    {
      value: "Obstetrics and Gynaecology",
      label: "Obstetrics and Gynaecology",
    },
    { value: "Clinical Haematology", label: "Clinical Haematology" },
    { value: "Nephrology", label: "Nephrology" },
    { value: "Medical Oncology", label: "Medical Oncology" },
    { value: "Endocrinology", label: "Endocrinology" },
    { value: "Cardiology", label: "Cardiology" },
    { value: "Pulmonary Medicine", label: "Pulmonary Medicine" },
    { value: "Neurology", label: "Neurology" },
    { value: "Gastroenterology", label: "Gastroenterology" },
    { value: "Hepatology", label: "Hepatology" },
    {
      value: "Clinical Immunology & Rheumatology",
      label: "Clinical Immunology & Rheumatology",
    },
    { value: "Infectious Disease", label: "Infectious Disease" },
    { value: "Critical Care Medicine", label: "Critical Care Medicine" },
    { value: "Medical Genetics", label: "Medical Genetics" },
    { value: "Geriatric Mental Health", label: "Geriatric Mental Health" },
    { value: "Neuroradiology", label: "Neuroradiology" },
    { value: "Interventional Radiology", label: "Interventional Radiology" },
    { value: "Cardiac Anesthesia", label: "Cardiac Anesthesia" },
    {
      value: "Organ Transplant Anesthesia & Critical Care",
      label: "Organ Transplant Anesthesia & Critical Care",
    },
    {
      value: "Pediatric and Neonatal Anesthesia",
      label: "Pediatric and Neonatal Anesthesia",
    },
    { value: "Pediatric Cardiology", label: "Pediatric Cardiology" },
    { value: "Neonatology", label: "Neonatology" },
    {
      value: "Pediatric Gastroenterology",
      label: "Pediatric Gastroenterology",
    },
    { value: "Pediatric Hepatology", label: "Pediatric Hepatology" },
    { value: "Pediatric Nephrology", label: "Pediatric Nephrology" },
    { value: "Pediatric Oncology", label: "Pediatric Oncology" },
    { value: "Clinical Pharmacology", label: "Clinical Pharmacology" },
    { value: "Onco-Pathology", label: "Onco-Pathology" },
    {
      value: "Plastic & Reconstructive Surgery",
      label: "Plastic & Reconstructive Surgery",
    },
    {
      value: "Hepatopancreato Biliary Surgery",
      label: "Hepatopancreato Biliary Surgery",
    },
    {
      value: "Surgical Gastroenterology (G.I. Surgery)",
      label: "Surgical Gastroenterology (G.I. Surgery)",
    },
    {
      value: "Urology (Genito-Urinary Surgery)",
      label: "Urology (Genito-Urinary Surgery)",
    },
    { value: "Vascular Surgery", label: "Vascular Surgery" },
    {
      value: "Cardio Vascular and Thoracic Surgery",
      label: "Cardio Vascular and Thoracic Surgery",
    },
    { value: "Thoracic Surgery", label: "Thoracic Surgery" },
    {
      value: "Pediatric Cardio Thoracic Vascular Surgery",
      label: "Pediatric Cardio Thoracic Vascular Surgery",
    },
    { value: "Endocrine Surgery", label: "Endocrine Surgery" },
    { value: "Surgical Oncology", label: "Surgical Oncology" },
    { value: "Head and Neck Surgery", label: "Head and Neck Surgery" },
    { value: "Hand Surgery", label: "Hand Surgery" },
    { value: "Rheumatology", label: "Rheumatology" },
    { value: "Diabetology", label: "Diabetology" },
    { value: "Pulmonology", label: "Pulmonology" },
    { value: "Hematology", label: "Hematology" },
    { value: "Pediatric Urology", label: "Pediatric Urology" },
    {
      value: "Allergology and Clinical Immunology",
      label: "Allergology and Clinical Immunology",
    },
    { value: "Orthopedic Odontology", label: "Orthopedic Odontology" },
    { value: "Oral Surgery", label: "Oral Surgery" },
    { value: "Pediatric Dentistry", label: "Pediatric Dentistry" },
    { value: "Orthodontics", label: "Orthodontics" },
    { value: "Maxillofacial Surgery", label: "Maxillofacial Surgery" },
    { value: "Materia Medica", label: "Materia Medica" },
    {
      value: "Organon of Medicine and Philosophy",
      label: "Organon of Medicine and Philosophy",
    },
    {
      value: "Case Taking and Repertorisation",
      label: "Case Taking and Repertorisation",
    },
    { value: "Practice of Medicine", label: "Practice of Medicine" },
    { value: "Pharmacy", label: "Pharmacy" },
    {
      value: "Social and Preventive HealthCare",
      label: "Social and Preventive HealthCare",
    },
    {
      value: "Homoeopathic Medicine & Surgery",
      label: "Homoeopathic Medicine & Surgery",
    },
    { value: "Electro-Homepathy", label: "Electro-Homepathy" },
    { value: "Clinical Diabetology", label: "Clinical Diabetology" },
    {
      value: "Preventive and Promotive Healthcare",
      label: "Preventive and Promotive Healthcare",
    },
    { value: "Health Science Research", label: "Health Science Research" },
    {
      value: "Hospital and Health Management",
      label: "Hospital and Health Management",
    },
    { value: "Food and Nutrition", label: "Food and Nutrition" },
    { value: "Medical Trichology", label: "Medical Trichology" },
    { value: "Pharmaceutical Management", label: "Pharmaceutical Management" },
    { value: "Diabetes Mellitus", label: "Diabetes Mellitus" },
    { value: "Acupuncture", label: "Acupuncture" },
    { value: "Maulik Siddhanta", label: "Maulik Siddhanta" },
    { value: "Rachana Sharir", label: "Rachana Sharir" },
    { value: "Kriya Sharir", label: "Kriya Sharir" },
    { value: "Ayurveda Samhita", label: "Ayurveda Samhita" },
    { value: "Swasthavritta", label: "Swasthavritta" },
    { value: "Dravyaguna Vijnana", label: "Dravyaguna Vijnana" },
    {
      value: "Rasa Shastra & Bhaishajbya Kalpana",
      label: "Rasa Shastra & Bhaishajbya Kalpana",
    },
    {
      value: "Rog Nidana & Vikriti Vigyana",
      label: "Rog Nidana & Vikriti Vigyana",
    },
    {
      value: "Agada Tantra, Vyavhar Ayurved & Vidhi Vaidyak",
      label: "Agada Tantra, Vyavhar Ayurved & Vidhi Vaidyak",
    },
    { value: "Kayachikitsa", label: "Kayachikitsa" },
    { value: "Kaumar Bhritya (Balroga)", label: "Kaumar Bhritya (Balroga)" },
    { value: "Panchakarma", label: "Panchakarma" },
    {
      value: "Prasuti Tantra Evam Stri Roga",
      label: "Prasuti Tantra Evam Stri Roga",
    },
    { value: "Shalya Tantra", label: "Shalya Tantra" },
    { value: "Shalakya Tantra", label: "Shalakya Tantra" },
    { value: "Agad Tantra", label: "Agad Tantra" },
    { value: "Bala Roga", label: "Bala Roga" },
    { value: "Dravya Guna", label: "Dravya Guna" },
    { value: "Maulika Siddhanta", label: "Maulika Siddhanta" },
    { value: "Roga & Vikriti Vijnana", label: "Roga & Vikriti Vijnana" },
    {
      value: "Rasa Shastra & Bhaishajya Kalpana Iatro-Chemistry",
      label: "Rasa Shastra & Bhaishajya Kalpana Iatro-Chemistry",
    },
    { value: "Sharira Rachana", label: "Sharira Rachana" },
    { value: "Sharira Kriya", label: "Sharira Kriya" },
    { value: "Rasayana & Vajikarana", label: "Rasayana & Vajikarana" },
    { value: "Kshar Karma", label: "Kshar Karma" },
    {
      value: "Ayurvedic Pharmaceutics Ras Shastra & Bhaishajya Kalpana",
      label: "Ayurvedic Pharmaceutics Ras Shastra & Bhaishajya Kalpana",
    },
    {
      value: "Ayurvedic Cosmetology & Skin Disease",
      label: "Ayurvedic Cosmetology & Skin Disease",
    },
    { value: "Ayurvedic Dietetics", label: "Ayurvedic Dietetics" },
    { value: "Swasthavritta and Yoga", label: "Swasthavritta and Yoga" },
    { value: "Prasuti & Striroga", label: "Prasuti & Striroga" },
    { value: "Balroga", label: "Balroga" },
    { value: "Dravyaguna", label: "Dravyaguna" },
    { value: "Manasik Swasthya Vigyan", label: "Manasik Swasthya Vigyan" },
    { value: "Netra Roga Vigyan", label: "Netra Roga Vigyan" },
    { value: "Ayurvedic Sangyaharana", label: "Ayurvedic Sangyaharana" },
    {
      value: "Chhaya avum Vikiran Vigyan",
      label: "Chhaya avum Vikiran Vigyan",
    },
    { value: "Marma avum Asthi Chikitsa", label: "Marma avum Asthi Chikitsa" },
    { value: "Rog Nidan Vidhi", label: "Rog Nidan Vidhi" },
    { value: "Aesthetic Dentistry", label: "Aesthetic Dentistry" },
    {
      value: "Orthodontics & Dentofacial Orthopedics",
      label: "Orthodontics & Dentofacial Orthopedics",
    },
    {
      value: "Conservative Dentistry & Endodontics",
      label: "Conservative Dentistry & Endodontics",
    },
    {
      value: "Prosthodontics and Crown & Bridge",
      label: "Prosthodontics and Crown & Bridge",
    },
    {
      value: "Pediatric and Preventive Dentistry",
      label: "Pediatric and Preventive Dentistry",
    },
    {
      value: "Oral and Maxillofacial Surgery",
      label: "Oral and Maxillofacial Surgery",
    },
    { value: "Periodontology", label: "Periodontology" },
    {
      value: "Oral Medicine and Radiology",
      label: "Oral Medicine and Radiology",
    },
    { value: "Pedodontics", label: "Pedodontics" },
    { value: "Community Dentistry", label: "Community Dentistry" },
  ],
};
