export const educationalQualifications = {
  degrees: {
    "Not Applicable": {
      postgraduateCourses: {
        "Not Applicable": ["Not Applicable"],
      },
    },
    MBBS: {
      postgraduateCourses: {
        "Not Applicable": ["Not Applicable"],
        MD: [
          "Not Applicable",
          "Medicine",
          "Dermatology, Venerology & Leprosy/DVL",
          "Chest & TB/Respiratory medicine",
          "Psychiatry",
          "Pediatrics",
          "Radiology/Radiodiagnosis",
          "Anesthesia",
          "Radiotherapy/Radiation Oncology",
          "Anatomy",
          "Physiology",
          "Pharmacology",
          "Microbiology",
          "P.S.M./Community Medicine",
          "Forensic Medicine",
          "Pathology",
          "Biochemistry",
          "Transfusion Medicine/ImmunoHaematology & Blood Transfusion",
          "Physical Medicine & Rehabilitation",
          "Palliative Medicine",
          "Nuclear Medicine",
          "Emergency Medicine",
          "Geriatrics",
        ],
        MS: [
          "Not Applicable",
          "General Surgery",
          "Orthopedics",
          "E.N.T./Otorhinolaryngology",
          "Ophthalmology",
          "OBGY",
        ],
        DNB: [
          "Not Applicable",
          "Anaesthesiology",
          "Ophthalmology",
          "Biochemistry",
          "Orthopedic Surgery",
          "Cardio Thoracic Surgery",
          "Dermatology and Venereology",
          "Emergency Medicine",
          "Pediatric Surgery",
          "Pediatrics",
          "Pathology",
          "ENT",
          "Family Medicine",
          "General Medicine",
          "General Surgery",
          "Pharmacology",
          "Physical Medicine and Rehabilitation",
          "Physiology",
          "Plastic Surgery",
          "Psychiatry",
          "Health Administration Including Hospital Administration",
          "Radio Diagnosis",
          "Immunohematology and Transfusion Medicine",
          "Radio Therapy",
          "Microbiology",
          "Respiratory Diseases",
          "Neuro Surgery",
          "Rural Surgery",
          "Nuclear Medicine",
          "Social and Preventive medicine",
          "Obstetrics and Gynaecology",
          "Forensic Medicine",
        ],
        Diploma: [
          "Not Applicable",
          "D.V.D. (Dermatology, Venerology and Leprosy)",
          "D.P.M. (Psychiatric Medicine)",
          "D.C.H. (Child Health)",
          "D.M.R.D. (Medical Radio-Diagnosis)",
          "D.M.R.T. / D. Medical Radiotherapy",
          "D.A. (Anesthesia)",
          "D.G.O. (Gynecology and Obstetrics)",
          "D.P.H. (Public Health/Community Medicine)",
          "D.F.M. (Family Medicine)",
          "D.T.C.D. (Tuberculosis and Chest Diseases)",
          "D.Ortho.",
          "D.O.R.L. (ENT)",
          "D.Opthal.",
          "D.C.P. (Pathology)",
          "D.D. (Diabetology)",
        ],
        DM: [
          "Not Applicable",
          "Clinical Haematology",
          "Nephrology",
          "Medical Oncology",
          "Endocrinology",
          "Cardiology",
          "Pulmonary Medicine",
          "Neurology",
          "Gastroenterology",
          "Hepatology",
          "Clinical Immunology & Rheumatology",
          "Infectious Disease",
          "Critical Care Medicine",
          "Medical Genetics",
          "Geriatric Mental Health",
          "Neuroradiology",
          "Interventional Radiology",
          "Cardiac Anesthesia",
          "Organ Transplant Anesthesia & Critical Care",
          "Pediatric and Neonatal Anesthesia",
          "Pediatric Cardiology",
          "Neonatology",
          "Pediatric Gastroenterology",
          "Pediatric Hepatology",
          "Pediatric Nephrology",
          "Pediatric Oncology",
          "Clinical Pharmacology",
          "Onco-Pathology",
        ],
        MCh: [
          "Not Applicable",
          "Plastic & Reconstructive Surgery",
          "Hepatopancreato Biliary Surgery",
          "Surgical Gastroenterology (G.I. Surgery)",
          "Urology (Genito-Urinary Surgery)",
          "Vascular Surgery",
          "Cardio Vascular and Thoracic Surgery",
          "Thoracic Surgery",
          "Pediatric Cardio Thoracic Vascular Surgery",
          "Neuro Surgery",
          "Endocrine Surgery",
          "Pediatric Surgery",
          "Surgical Oncology",
          "Head and Neck Surgery",
          "Hand Surgery",
        ],
        Fellowship: [
          "Not Applicable",
          "Clinical Cardiology",
          "Rheumatology",
          "Family Medicine",
          "General Endocrinology",
          "Diabetology",
          "Pulmonology",
          "General Psychiatry",
          "Orthopaedics",
          "Radiation Oncology",
          "Dermatovenereology",
          "Hematology",
          "Radiology",
          "Neurosurgery",
          "Cardiology",
          "Pediatric Urology",
          "Allergology and Clinical Immunology",
          "Ophthalmology",
          "Orthopedic Odontology",
          "Oral Surgery",
          "Pediatric Dentistry",
          "Orthodontics",
          "Maxillofacial Surgery",
        ],
      },
    },
    BHMS: {
      postgraduateCourses: {
        "Not Applicable": ["Not Applicable"],
        MD: [
          "Not Applicable",
          "Psychiatry",
          "Materia Medica",
          "Organon of Medicine and Philosophy",
          "Case Taking and Repertorisation",
          "Practice of Medicine",
          "Pediatrics",
          "Pharmacy",
        ],
        Diploma: [
          "Not Applicable",
          "Social and Preventive HealthCare",
          "Homoeopathic Medicine & Surgery",
          "Electro-Homepathy",
          "Clinical Diabetology",
          "Preventive and Promotive Healthcare",
          "Health Science Research",
          "Hospital and Health Management",
          "Food and Nutrition",
          "Medical Trichology",
          "Pharmaceutical Management",
          "Diabetes Mellitus",
          "Acupuncture",
        ],
      },
    },
    BAMS: {
      postgraduateCourses: {
        "Not Applicable": ["Not Applicable"],
        "MD/MS": [
          "Not Applicable",
          "Maulik Siddhanta",
          "Rachana Sharir",
          "Kriya Sharir",
          "Ayurveda Samhita",
          "Swasthavritta",
          "Dravyaguna Vijnana",
          "Rasa Shastra & Bhaishajbya Kalpana",
          "Rog Nidana & Vikriti Vigyana",
          "Agada Tantra, Vyavhar Ayurved & Vidhi Vaidyak",
          "Kayachikitsa",
          "Kaumar Bhritya (Balroga)",
          "Panchakarma",
          "Prasuti Tantra Evam Stri Roga",
          "Shalya Tantra",
          "Shalakya Tantra",
          "MD Agad Tantra",
          "MD Bala Roga",
          "MD Dravya Guna",
          "MD Kayachikitsa",
          "MD Maulika Siddhanta",
          "MD Panchakarma",
          "MD Roga & Vikriti Vijnana",
          "MD Rasa Shastra & Bhaishajya Kalpana Iatro-Chemistry",
          "MD Sharira Rachana",
          "MD Sharira Kriya",
          "MD Swasthya Vritta",
          "MD Rasayana & Vajikarana",
        ],
        Diploma: [
          "Not Applicable",
          "Panchakarma",
          "Kshar Karma",
          "Ayurvedic Pharmaceutics Ras Shastra & Bhaishajya Kalpana",
          "Ayurvedic Cosmetology & Skin Disease",
          "Ayurvedic Dietetics",
          "Swasthavritta and Yoga",
          "Prasuti & Striroga",
          "Balroga",
          "Dravyaguna",
          "Manasik Swasthya Vigyan",
          "Netra Roga Vigyan",
          "Rasayan and Vajikaran",
          "Ayurvedic Sangyaharana",
          "Chhaya avum Vikiran Vigyan",
          "Marma avum Asthi Chikitsa",
          "Rog Nidan Vidhi",
        ],
      },
    },
    BDS: {
      postgraduateCourses: {
        "Not Applicable": ["Not Applicable"],
        Diploma: [
          "Not Applicable",
          " Aesthetic Dentistry",
          "Orthodontics & Dentofacial Orthopedics",
          "Conservative Dentistry & Endodontics",
          "Prosthodontics and Crown & Bridge",
          "Pediatric and Preventive Dentistry",
          "Oral and Maxillofacial Surgery",
          "Periodontology",
        ],
        MDS: [
          "Not Applicable",
          "Oral and Maxillofacial Surgery",
          "Orthodontics",
          "Prosthodontics",
          "Periodontology",
          "Oral Medicine and Radiology",
          "Pedodontics",
          "Conservative Dentistry and Endodontics",
          "Oral Pathology",
          "Community Dentistry",
        ],
      },
    },
  },
};
