export const nurse_qualifications = {
  degree: ["ANM", "GNM", "BSc Nursing", "BSc Nursing (Post Basic)"],
  postgraduate: [
    "Not Applicable",
    "MSc Nursing",
    "Post Basic Diploma Nursing",
    "Fellowship in Nursing",
    "Certificate Course",
  ],
  specialization: [
    "Not Applicable",
    "Critical Care Nursing",
    "Cardiovascular & Thoracic Nursing",
    "Operation Room (OT) Nursing",
    "Neonatal Nursing",
    "Orthopedic and Rehabilitation Nursing",
    "Emergency and Trauma Nursing",
    "Oncology Nursing",
    "Nephrology Nursing",
    "Psychiatric Nursing",
    "Community Health Nursing",
    "Palliative Care Nursing",
    "Burn and Plastic Surgery Nursing",
    "Infection Control Nursing",
    "Geriatric Nursing",
    "Medical - Surgical Nursing",
    "Obstetrics and Gynaecological Nursing",
    "Pediatric Nursing",
    "Dialysis Nursing",
  ],
};
