export const stateCityData = {
  "Andhra Pradesh": [
    "Amaravati",
    "Vijayawada",
    "Visakhapatnam",
    "Guntur",
    "Nellore",
    "Tirupati",
    "Kakinada",
    "Anantapur",
    "Kadapa",
    "Rajahmundry",
    "Addanki",
    "Addatigala",
    "Adoni",
    "Ahobilam",
    "Ainavolu",
    "Alampur",
    "Alipur",
    "Allagadda",
    "Alur",
    "Amalapuram",
    "Ambur",
    "Anakapalle",
    "Annavaram",
    "Araku Valley",
    "Atmakur",
    "Atmakuru",
    "Avanigadda",
    "Ayirāla",
    "Badvel",
    "Bagepalli",
    "Ballari",
    "Banganapalli",
    "Bangarapet",
    "Bapatla",
    "Benz Circle",
    "Bhadrāchalam",
    "Bheemili",
    "Bheemulavaripalem",
    "Bhimavaram",
    "Bhimunipatnam",
    "Bhogopuram",
    "Bobbili",
    "Brahmapur",
    "Buckinghampet",
    "Challakere",
    "Chandragiri",
    "Chintalapudi",
    "Chintamani",
    "Chintapalle",
    "Chipurupalle",
    "Chirala",
    "Chittoor",
    "Chodavaram",
    "Darsi",
    "Dharmavaram",
    "Dhone",
    "Dindi",
    "Draksharama",
    "Dwaraka Tirumala",
    "Eluru",
    "Gajapatinagaram",
    "Gandikota",
    "Gannavaram",
    "Gauribidanur",
    "Giddalur",
    "Gooty",
    "Gudibanda",
    "Gudivada",
    "Gudiyatham",
    "Gudur",
    "Gummidipundi",
    "Guntakal",
    "Gunupur",
    "Guruzala",
    "Hindupur",
    "Hiriyur",
    "Horsley Hills",
    "Ichchapuram",
    "Irukkam Island",
    "Jaggayyapeta",
    "Jammalamadugu",
    "Jangareddigudem",
    "Kadiri",
    "Kaikalur",
    "Kalyandurg",
    "Kamalapuram",
    "Kanakammachattram",
    "Kandukur",
    "Kanigiri",
    "Kanipakam",
    "Katpadi",
    "Kavali",
    "Kavutaram",
    "Koilkuntla",
    "Kolhapur",
    "Kondapalle",
    "Konta",
    "Kottapeta",
    "Kovvur",
    "Koyyalagūdem",
    "Krishnagiri",
    "Krīshnāpatnam",
    "Kuppam",
    "Kurnool",
    "Lambasingi",
    "Lepakshi",
    "Machilipatnam",
    "Madakasira",
    "Madanapalle",
    "Madhira",
    "Madhugiri",
    "Madkar",
    "Malakanagiri",
    "Mandapeta",
    "Mangalagiri",
    "Mantralayam",
    "Manvi",
    "Maredumilli",
    "Markapur",
    "Molakalmuru",
    "Mopidevi",
    "Mulapadava",
    "Mulbagal",
    "Mummidivaram",
    "Muttukadu",
    "Nandigama",
    "Nandikotkur",
    "Nandyal",
    "Narasaraopet",
    "Narsannapeta",
    "Narsapur",
    "Narsipatnam",
    "Nidadavolu",
    "Nuzvid",
    "Ongole",
    "Paderu",
    "Palakollu",
    "Palakonda",
    "Pallippattu",
    "Palmaner",
    "Paralakhemundi",
    "Parvathipuram",
    "Pathapatnam",
    "Pattikonda",
    "Pavagada",
    "Peddapuram",
    "Penukonda",
    "Pithapuram",
    "Podili",
    "Polavaram",
    "Ponneri",
    "Prathipadu",
    "Proddatur",
    "Pudi",
    "Pulivendla",
    "Punganuru",
    "Puspatirega",
    "Puttaparthi",
    "Puttur",
    "Raichur",
    "Ramachandrapuram",
    "Ramarajulanka",
    "Ramathirtham",
    "Rampa Chodavaram",
    "Rapur",
    "Rayachoti",
    "Rayadurg",
    "Rayagarha",
    "Renigunta",
    "Repalle",
    "Rāzole",
    "Salur",
    "Samarlakota",
    "Sandur",
    "Sattenapalle",
    "Satyavedu",
    "Sira",
    "Siruguppa",
    "Sompeta",
    "Sriharikota",
    "Srikakulam",
    "Srikalahasti",
    "Srinivaspur",
    "Srisailam",
    "Srungavarapukota",
    "Tada",
    "Tadpatri",
    "Tanuku",
    "Tekkali",
    "Tenali",
    "Tiruchanur",
    "Tirumala",
    "Tiruvallur",
    "Tiruvuru",
    "Tuni",
    "Tādepallegūdem",
    "Udayagiri",
    "Uttukkottai",
    "Vaniyambadi",
    "Vayalipad",
    "Venadu",
    "Venkatagiri",
    "Vinukonda",
    "Vizianagaram",
    "Yanam",
    "Yellamanchili",
    "Yemmiganur",
  ],
  "Arunachal Pradesh": [
    "Itanagar",
    "Naharlagun",
    "Pasighat",
    "Ziro",
    "Tezu",
    "Tawang",
    "Aalo",
    "Daporijo",
    "Namsai",
    "Roing",
    "Khonsa",
    "Namsai",
    "East Siang",
    "Seppa",
    "Bomdila",
    "Dirang",
    "Aalo",
    "Daporijo",
    "Anini",
    "Changlang",
    "Jairampur",
    "Hawai",
    "Bordumsa",
    "Gandhigram",
    "Chowkham",
    "Tawang",
    "Wakro",
    "Yingkiong",
    "Pangin",
    "Nyapin",
    "Boleng",
    "Gelling",
    "Thingbu",
    "Sagalee",
    "Basar",
    "Dirang H.Q.",
    "Kalaktang",
    "Nacho",
    "Bameng",
    "Dambuk",
    "Mipi",
    "Zemithang",
    "Thembang",
    "Vijoynagar",
    "Lathao",
    "Bhalukpong",
    "Yupia",
    "Ruksin",
    "Bhismaknagar",
    "Kumki",
    "Namsang",
    "Hayuliang",
    "Yachuli",
    "Mechuka",
    "Taliha",
  ],
  Assam: [
    "Guwahati",
    "Dibrugarh",
    "Silchar",
    "Jorhat",
    "Nagaon",
    "Tinsukia",
    "Tezpur",
    "Bongaigaon",
    "Diphu",
    "Karimganj",
    "Sivasagar",
    "Goalpara",
    "Golaghat",
    "Lakhimpur",
    "Barpeta",
    "Kokrajhar",
    "Hailakandi",
    "Udalguri",
    "Dhemaji",
    "Chirang",
    "Morigaon",
    "Sonitpur",
    "Dhubri",
    "Nalbari",
    "North Lakhimpur",
    "Mangaldoi",
    "Rangia",
    "Biswanath Chariali",
    "Hojai",
    "Titabor",
    "Margherita",
    "Naharkatia",
    "Majuli",
    "Tinsukia",
    "Bokakhat",
    "Sarupathar",
    "Lumding",
    "Duliajan",
    "Jagiroad",
    "Charaideo",
    "Rangapara",
    "Mariani",
    "Sonari",
    "Bilasipara",
    "Sadiya",
    "Lakhipur",
    "Howraghat",
    "Moran",
    "Haflong",
    "Sualkuchi",
    "Pathsala",
    "Gohpur",
    "Moranhat",
    "Bokajan",
    "Nalbari",
    "Barama",
    "Jalukbari",
    "Kamrup",
    "Kampur",
    "Baihata Chariali",
    "Tamulpur",
    "Jonai",
    "Gauripur",
    "Raha",
    "Abhayapuri",
    "Makum",
    "Morigaon",
    "Palashbari",
    "Nalbari",
  ],
  Bihar: [
    "Patna",
    "Gaya",
    "Bhagalpur",
    "Muzaffarpur",
    "Darbhanga",
    "Purnia",
    "Arrah",
    "Begusarai",
    "Katihar",
    "Munger",
    "Chhapra",
    "Bihar Sharif",
    "Hajipur",
    "Dehri",
    "Siwan",
    "Motihari",
    "Saharsa",
    "Sasaram",
    "Nawada",
    "Bettiah",
    "Jamalpur",
    "Sitamarhi",
    "Supaul",
    "Lakhisarai",
    "Bagaha",
    "Supaul",
    "Buxar",
    "Jehanabad",
    "Aurangabad",
    "Rajgir",
    "Madhubani",
    "Samastipur",
    "Bhabua",
    "Jamui",
    "Araria",
    "Kishanganj",
    "Madhepura",
    "Sheohar",
    "Khagaria",
    "Gopalganj",
    "Banka",
    "Saran",
    "Sheikhpura",
    "Raxaul",
    "Forbesganj",
    "Masaurhi",
    "Narkatiaganj",
    "Haripur",
    "Bakhtiyarpur",
    "Maner",
    "Phulwari Sharif",
    "Fatuha",
    "Bihta",
    "Mokama",
    "Jamui",
    "Islampur",
    "Hilsa",
    "Ekangarsarai",
    "Piro",
    "Shahpur",
    "Arwal",
    "Dumraon",
    "Barh",
    "Raxaul",
    "Daudnagar",
    "Shiekhpura",
    "Mahnar Bazar",
    "Rosera",
    "Sugauli",
    "Khagaul",
    "Madhubani",
    "Nawada",
    "Dighwara",
    "Shahpur",
    "Sugauli",
    "Amarpur",
    "Pipra",
    "Bikramganj",
    "Mahua",
    "Chakia",
    "Areraj",
    "Jagdishpur",
    "Rajauli",
    "Chandi",
    "Sonpur",
    "Chand",
    "Gogri Jamalpur",
    "Kasba",
    "Narpatganj",
    "Kusheshwar Asthan",
    "Paliganj",
    "Tekari",
    "Dalsinghsarai",
    "Marhaura",
    "Arwal",
    "Asthawan",
    "Benipatti",
    "Belsand",
    "Bhabua",
    "Bhojpur",
    "Ekma",
    "Jaynagar",
    "Kasba",
    "Kurtha",
    "Lalganj",
    "Maharajganj",
    "Marhaura",
    "Motipur",
    "Nabinagar",
    "Phulwari Sharif",
    "Ramgarhwa",
    "Rosera",
    "Sandesh",
    "Sheohar",
    "Sonepur",
    "Thakurganj",
    "Triveniganj",
    "Warisaliganj",
  ],
  Chhattisgarh: [
    "Raipur",
    "Bhilai",
    "Korba",
    "Bilaspur",
    "Durg",
    "Rajnandgaon",
    "Jagdalpur",
    "Raigarh",
    "Ambikapur",
    "Mahasamund",
    "Dhamtari",
    "Champa",
    "Kawardha",
    "Kondagaon",
    "Chirmiri",
    "Sukma",
    "Manendragarh",
    "Surajpur",
    "Balod",
    "Dongargarh",
    "Bemetara",
    "Tilda",
    "Mungeli",
    "Pandariya",
    "Baloda Bazar",
    "Dantewada",
    "Janjgir",
    "Bhatapara",
    "Gariaband",
    "Saraipali",
    "Kanker",
    "Naila Janjgir",
    "Koriya",
    "Narayanpur",
    "Pathalgaon",
    "Bijapur",
    "Dalli Rajhara",
    "Khairagarh",
    "Pendra",
    "Basna",
    "Palari",
    "Arang",
    "Patan",
    "Pusaur",
    "Dhamdha",
    "Bilha",
    "Katghora",
    "Baramkela",
    "Sakti",
    "Balrampur",
    "Ratanpur",
    "Lormi",
    "Gaurela",
    "Raghunathpur",
    "Gandai",
    "Deori",
    "Saraipali",
    "Dharamjaigarh",
    "Pratappur",
    "Antagarh",
    "Masturi",
    "Pali",
    "Charama",
    "Chhuikhadan",
    "Rajim",
    "Jamgaon",
    "Bade Bacheli",
    "Sarangarh",
    "Gidam",
    "Marwahi",
    "Nagri",
    "Gharghoda",
    "Sihawa",
    "Shivrinarayan",
    "Baramkela",
    "Saja",
    "Pasan",
    "Saragaon",
    "Keshkal",
    "Bhopalpatnam",
    "Dabhra",
    "Jhagrakhand",
    "Bhanupratappur",
    "Kondagaon",
    "Pakhanjur",
    "Banswara",
  ],
  Goa: [
    "Panaji",
    "Margao",
    "Vasco da Gama",
    "Mapusa",
    "Ponda",
    "Bicholim",
    "Curchorem",
    "Quepem",
    "Sanguem",
    "Sanquelim",
    "Canacona",
    "Valpoi",
    "Mormugao",
    "Tiswadi",
    "Salcete",
    "Pernem",
    "Bardez",
    "Sattari",
    "Dharbandora",
    "Pernem",
    "Bardez",
    "Anjuna",
    "Calangute",
    "Candolim",
    "Arpora",
    "Assagao",
    "Porvorim",
    "Aldona",
    "Chimbel",
    "Reis Magos",
    "Sinquerim",
    "Nerul",
    "Pilerne",
    "Santa Cruz",
    "Taleigao",
    "Chorao",
    "Divar",
    "St. Estevam",
    "Cortalim",
    "Betim",
    "Mandrem",
    "Morjim",
    "Pernem",
    "Sankhali",
    "Mollem",
    "Tivim",
    "Siolim",
    "Loutolim",
    "Raia",
    "Majorda",
    "Colva",
    "Benaulim",
    "Varca",
    "Cavelossim",
    "Assolna",
    "Betul",
    "Canacona",
    "Agonda",
    "Palolem",
    "Kankon",
    "Chaudi",
    "Pale",
  ],
  Gujarat: [
    "Ahmedabad",
    "Surat",
    "Vadodara",
    "Rajkot",
    "Gandhinagar",
    "Bhavnagar",
    "Jamnagar",
    "Junagadh",
    "Anand",
    "Mehsana",
    "Navsari",
    "Gondal",
    "Vapi",
    "Gandhidham",
    "Morbi",
    "Dahod",
    "Palanpur",
    "Patan",
    "Surendranagar",
    "Kheda",
    "Aravalli",
    "Dang",
    "Modasa",
    "Khambhalia",
    "Daman",
    "Bharuch",
    "Valsad",
    "Sidhpur",
    "Bhuj",
    "Porbandar",
    "Maliya",
    "Kankrej",
    "Chhota Udaipur",
    "Narmada",
    "Wadhwan",
    "Saurashtra",
    "Upleta",
    "Rajpipla",
    "Dabhoi",
  ],
  Haryana: [
    "Chandigarh",
    "Faridabad",
    "Gurgaon",
    "Panipat",
    "Ambala",
    "Hisar",
    "Karnal",
    "Sonipat",
    "Rohtak",
    "Yamunanagar",
    "Sirsa",
    "Jind",
    "Fatehabad",
    "Bhiwani",
    "Panchkula",
    "Mahendragarh",
    "Rewari",
    "Jhajjar",
    "Palwal",
    "Kaithal",
    "Kurukshetra",
    "Narnaul",
    "Shahabad",
    "Hansi",
    "Pinjore",
    "Bawal",
    "Tohana",
    "Ratia",
    "Sarsod",
    "Gohana",
    "Ambala Cantt",
    "Badli",
    "Mewat",
    "Assandh",
    "Samalkha",
    "Nuh",
    "Firozpur Jhirka",
  ],
  "Himachal Pradesh": [
    "Shimla",
    "Dharamshala",
    "Manali",
    "Solan",
    "Mandi",
    "Una",
    "Palampur",
    "Hamirpur",
    "Kullu",
    "Chamba",
  ],
  Jharkhand: [
    "Ranchi",
    "Jamshedpur",
    "Dhanbad",
    "Bokaro Steel City",
    "Deoghar",
    "Hazaribagh",
    "Giridih",
    "Ramgarh",
    "Phusro",
    "Medininagar",
  ],
  Karnataka: [
    "Bengaluru",
    "Mysuru",
    "Mangalore",
    "Hubballi",
    "Belagavi",
    "Davangere",
    "Ballari",
    "Vijayapura",
    "Shivamogga",
    "Tumakuru",
  ],
  Kerala: [
    "Thiruvananthapuram",
    "Kochi",
    "Kozhikode",
    "Thrissur",
    "Kollam",
    "Kannur",
    "Alappuzha",
    "Palakkad",
    "Kottayam",
    "Malappuram",
  ],
  "Madhya Pradesh": [
    "Bhopal",
    "Indore",
    "Gwalior",
    "Jabalpur",
    "Ujjain",
    "Sagar",
    "Satna",
    "Dewas",
    "Ratlam",
    "Rewa",
  ],
  Maharashtra: [
    "Mumbai",
    "Pune",
    "Nagpur",
    "Nashik",
    "Aurangabad",
    "Thane",
    "Solapur",
    "Kolhapur",
    "Jalgaon",
    "Amravati",
    "Ulhasnagar",
    "Nanded",
    "Sangli",
    "Latur",
    "Ahmednagar",
    "Satara",
    "Akola",
    "Chandrapur",
    "Bhusawal",
    "Ichalkaranji",
    "Panvel",
    "Karad",
    "Ratnagiri",
    "Parbhani",
    "Jalna",
    "Navi Mumbai",
    "Dombivli",
    "Kalyan",
    "Sangamner",
    "Pimpri-Chinchwad",
    "Bhiwandi",
    "Wardha",
    "Osmanabad",
    "Shirdi",
    "Dhule",
    "Nashik Road",
    "Kurduwadi",
    "Sinnar",
    "Raver",
    "Buldhana",
    "Chopda",
    "Pali",
    "Gondia",
    "Mira-Bhayandar",
    "Panvel",
    "Vasai-Virar",
    "Matheran",
    "Alibaug",
    "Malvan",
    "Nandurbar",
    "Navi Mumbai",
    "Khopoli",
    "Dadra and Nagar Haveli",
    "Daman",
    "Silvassa",
    "Vapi",
  ],
  Manipur: [
    "Imphal",
    "Thoubal",
    "Bishnupur",
    "Churachandpur",
    "Kakching",
    "Ukhrul",
    "Senapati",
    "Tamenglong",
    "Chandel",
    "Moreh",
  ],
  Meghalaya: [
    "Shillong",
    "Tura",
    "Nongpoh",
    "Jowai",
    "Baghmara",
    "Williamnagar",
    "Cherrapunji",
    "Mairang",
  ],
  Mizoram: [
    "Aizawl",
    "Lunglei",
    "Serchhip",
    "Champhai",
    "Kolasib",
    "Lawngtlai",
    "Mamit",
    "Saiha",
    "Bairabi",
  ],
  Nagaland: [
    "Kohima",
    "Dimapur",
    "Mokokchung",
    "Tuensang",
    "Wokha",
    "Zunheboto",
    "Mon",
    "Phek",
    "Kiphire",
    "Longleng",
  ],
  Odisha: [
    "Bhubaneswar",
    "Cuttack",
    "Rourkela",
    "Berhampur",
    "Sambalpur",
    "Puri",
    "Balasore",
    "Baripada",
    "Bhadrak",
    "Angul",
  ],
  Punjab: [
    "Chandigarh",
    "Ludhiana",
    "Amritsar",
    "Jalandhar",
    "Patiala",
    "Bathinda",
    "Hoshiarpur",
    "Mohali",
    "Pathankot",
    "Moga",
  ],
  Rajasthan: [
    "Jaipur",
    "Jodhpur",
    "Udaipur",
    "Kota",
    "Bikaner",
    "Ajmer",
    "Alwar",
    "Bharatpur",
    "Bhilwara",
    "Sikar",
  ],
  Sikkim: [
    "Gangtok",
    "Namchi",
    "Geyzing",
    "Mangan",
    "Rangpo",
    "Singtam",
    "Jorethang",
    "Pakyong",
    "Ravangla",
  ],
  "Tamil Nadu": [
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Tiruchirappalli",
    "Salem",
    "Tirunelveli",
    "Erode",
    "Vellore",
    "Thoothukudi",
    "Thanjavur",
  ],
  Telangana: [
    "Hyderabad",
    "Warangal",
    "Nizamabad",
    "Karimnagar",
    "Khammam",
    "Ramagundam",
    "Mahbubnagar",
    "Nalgonda",
    "Suryapet",
    "Adilabad",
  ],
  Tripura: [
    "Agartala",
    "Udaipur",
    "Dharmanagar",
    "Kailasahar",
    "Ambassa",
    "Belonia",
    "Kamalpur",
    "Sonamura",
    "Melaghar",
    "Sabroom",
  ],
  "Uttar Pradesh": [
    "Lucknow",
    "Kanpur",
    "Agra",
    "Varanasi",
    "Ghaziabad",
    "Meerut",
    "Prayagraj",
    "Bareilly",
    "Aligarh",
    "Moradabad",
  ],
  Uttarakhand: [
    "Dehradun",
    "Haridwar",
    "Nainital",
    "Roorkee",
    "Haldwani",
    "Rudrapur",
    "Kashipur",
    "Rishikesh",
    "Pithoragarh",
    "Almora",
  ],
  "West Bengal": [
    "Kolkata",
    "Howrah",
    "Durgapur",
    "Siliguri",
    "Asansol",
    "Darjeeling",
    "Malda",
    "Kharagpur",
    "Haldia",
    "Bardhaman",
  ],
  "Andaman and Nicobar Islands": [
    "Port Blair",
    "Garacharma",
    "Prothrapur",
    "Bombooflat",
    "Rangat",
    "Diglipur",
    "Mayabunder",
    "Hut Bay",
  ],
  Chandigarh: ["Chandigarh"],
  "Dadra and Nagar Haveli and Daman and Diu": [
    "Silvassa",
    "Daman",
    "Diu",
    "Amli",
    "Khadoli",
    "Samarvarni",
    "Naroli",
    "Vapi",
  ],
  Lakshadweep: [
    "Kavaratti",
    "Agatti",
    "Andrott",
    "Minicoy",
    "Amini",
    "Kalpeni",
    "Kadmat",
  ],
  Delhi: [
    "Connaught Place",
    "New Delhi",
    "South Delhi",
    "North Delhi",
    "East Delhi",
    "West Delhi",
    "Central Delhi",
    "Rohini",
    "Dwarka",
    "Vasant Kunj",
    "Hauz Khas",
    "Green Park",
    "Greater Kailash",
    "Punjabi Bagh",
    "Pitampura",
    "Karol Bagh",
    "Rajouri Garden",
    "Janakpuri",
    "Lajpat Nagar",
    "Chandni Chowk",
    "Delhi Cantonment",
    "Saket",
    "Mukherjee Nagar",
    "Rani Bagh",
    "Sarai Rohilla",
    "Preet Vihar",
    "Mandi House",
    "Jamia Nagar",
    "Okhla",
    "Vikas Puri",
    "Shalimar Bagh",
    "Nehru Place",
    "Civil Lines",
    "Bengali Market",
    "Kalkaji",
    "Paschim Vihar",
    "Sarai Julena",
    "Pitam Pura",
    "Delhi University",
    "Ghazipur",
    "Sultanpur",
    "Darya Ganj",
    "Sarai Kale Khan",
    "Rohini Sector 7",
    "Rohini Sector 16",
    "Kalkaji Extension",
    "Burari",
    "Jangpura",
    "Molar Band",
    "Bawana",
    "Najafgarh",
    "Bara Hindu Rao",
    "Harsingh Bagh",
    "Shahdara",
    "Vasant Vihar",
    "Chattarpur",
    "Mahipalpur",
    "Nangloi",
    "Paharganj",
  ],
  Puducherry: ["Puducherry", "Karaikal", "Mahe", "Yanam"],
  Ladakh: ["Leh", "Kargil", "Nubra", "Zanskar", "Diskit", "Tangtse", "Sankoo"],
  "Jammu and Kashmir": [
    "Srinagar",
    "Jammu",
    "Anantnag",
    "Baramulla",
    "Kathua",
    "Udhampur",
    "Sopore",
    "Kupwara",
    "Pulwama",
    "Poonch",
  ],
};
